version: "3.7"

services:
  ckan:
    container_name: ckan
    image: ckancontainerreg.azurecr.io/prod/ckan:2.8.3.latest
    logging:
      driver: "json-file"
      options:
         max-size: "150K"
         max-file: "10"
    environment:
      - POSTGRESQL_SERVICE=${POSTGRESQL_SERVICE}
      - CKAN_SQLALCHEMY_URL=postgresql://${POSTGRES_USER}%40${POSTGRESQL_SERVICE}:${POSTGRES_PASSWORD}@${POSTGRESQL_SERVICE}.${POSTGRESQL_SERVICE_DOMAIN}:5432/${DATABASE_ENV}ckan?sslmode=require
      - CKAN_DATASTORE_WRITE_URL=postgresql://${POSTGRES_USER}%40${POSTGRESQL_SERVICE}:${POSTGRES_PASSWORD}@${POSTGRESQL_SERVICE}.${POSTGRESQL_SERVICE_DOMAIN}:5432/${DATABASE_ENV}datastore?sslmode=require
      - CKAN_DATASTORE_READ_URL=postgresql://${DATASTORE_USER}%40${POSTGRESQL_SERVICE}:${DS_RO_PASS}@${POSTGRESQL_SERVICE}.${POSTGRESQL_SERVICE_DOMAIN}:5432/${DATABASE_ENV}datastore?sslmode=require
      - TEST_CKAN_SQLALCHEMY_URL=postgresql://${POSTGRES_USER}%40${POSTGRESQL_SERVICE}:${POSTGRES_PASSWORD}@${POSTGRESQL_SERVICE}.${POSTGRESQL_SERVICE_DOMAIN}:5432/${DATABASE_ENV}ckan_tst?sslmode=require
      - TEST_CKAN_DATASTORE_WRITE_URL=postgresql://${POSTGRES_USER}%40${POSTGRESQL_SERVICE}:${POSTGRES_PASSWORD}@${POSTGRESQL_SERVICE}.${POSTGRESQL_SERVICE_DOMAIN}:5432/${DATABASE_ENV}datastore_tst?sslmode=require
      - TEST_CKAN_DATASTORE_READ_URL=postgresql://${DATASTORE_USER}%40${POSTGRESQL_SERVICE}:${DS_RO_PASS}@${POSTGRESQL_SERVICE}.${POSTGRESQL_SERVICE_DOMAIN}:5432/${DATABASE_ENV}datastore_tst?sslmode=require
      - TEST_CKAN_SOLR_URL=${TEST_CKAN_SOLR_URL}
      - TEST_CKAN_REDIS_URL=${TEST_CKAN_REDIS_URL}
    links:
# Commented out to use POSTGRESQL instead of docker db
#     - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
#    restart: always
    
  datapusher:
    container_name: datapusher
    image: ckancontainerreg.azurecr.io/prod/datapusher:latest
    logging:
      driver: "json-file"
      options:
         max-size: "150K"
         max-file: "10"
    ports:
      - "8800:8800"
    restart: always

  solr:
    container_name: solr
    image: ckancontainerreg.azurecr.io/prod/solr:latest
    logging:
      driver: "json-file"
      options:
         max-size: "150K"
         max-file: "10"
    ports:
      - "8983:8983"
    restart: always
    
  redis:
    container_name: redis
    image: redis:alpine
    logging:
      driver: "json-file"
      options:
         max-size: "150K"
         max-file: "10"
    restart: always
    
volumes:
  ckan_storage:
